### PR TITLE
Modernize and remove underscore dependency

### PR DESCRIPTION
**Pull request by sebakerckhof**
@tmeasday This was one of the last dependencies of our app that kept including underscore in our bundle.
I took the time to modernize it while removing the underscore package

### CODE REVIEW

**Comment by tmeasday** [comment]
@sebakerckhof - I've added you as a maintainer to the repo.

I don't seem to be able to give you publish rights to the package: 

image

Not sure what's going on there...

**Comment by sebakerckhof** [comment]
@tmeasday it's because my meteor username is just `seba`

**Comment by tmeasday** [comment]
@sebakerckhof cool, done now.

**Comment by sebakerckhof** [comment]
Thanks!

**Pull request merged**
